### ISSUE TITLE
プレイヤーのアニメーション

### ISSUE THREAD

**Issue by yusei-shiraishi2929** [GowanTEKERU/GowanTAKERU#9]

**Comment by yusei-shiraishi2929** [comment]
簡易アニメーションを追加しました

**Comment by taishi-matsumura** [comment]
@shirapi コミット時のコメントに issue #9 みたいに書いておくと自動的にそのissueにコミットログが表示されるようになるので、わざわざissueにコメントを書く必要なくなります。

コミットコメントの先頭行を
`[issue #9]簡易アニメーションを追加`
みたいにしておくのが一般的みたい。
そうしておくとコミットの一覧(https://github.com/GowanTEKERU/GowanTAKERU/commits/master) からそのissueに飛べるようになるので便利です。
